# Generated by Django 3.2.22 on 2023-11-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glossary',
            name='unique_glossary_item',
        ),
    ]
