# Generated by Django 3.2.22 on 2023-10-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='../default-user_fqha9k', upload_to='cinematography/'),
        ),
    ]
